# Generated by Django 6.0.3 on 2026-03-30 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaBovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría bovina',
                'verbose_name_plural': 'Categorías bovinas',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Cultura')),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DestinoProductivoBovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Destino productivo bovino',
                'verbose_name_plural': 'Destinos productivos bovinos',
            },
        ),
        migrations.CreateModel(
            name='EstadoReproductivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Estado reproductivo',
                'verbose_name_plural': 'Estados reproductivos',
            },
        ),
        migrations.CreateModel(
            name='RazaBovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Raza bovina',
                'verbose_name_plural': 'Razas bovinas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del campo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('superficie_ha', models.DecimalField(decimal_places=2, help_text='Superficie total del campo expresada en hectáreas', max_digits=10, verbose_name='Superficie total')),
                ('image', models.ImageField(default='default.jpg', upload_to='campos', verbose_name='Imagen')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agro_campos', to='agro.ciudad', verbose_name='Ciudad / Localidad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agro_campos', to='agro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establecimientos', to='agro.ciudad', verbose_name='Ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establecimientos', to='agro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='AnimalBovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('caravana_senasa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Caravana SENASA')),
                ('tatuaje', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tatuaje')),
                ('nombre_apodo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre o apodo')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='gestion_bovinos.animalbovino', verbose_name='Madre')),
                ('categoria_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion_bovinos.categoriabovino', verbose_name='Categoría actual')),
                ('destino_productivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion_bovinos.destinoproductivobovino', verbose_name='Destino productivo')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion_bovinos.establecimiento', verbose_name='Establecimiento')),
                ('estado_reproductivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion_bovinos.estadoreproductivo', verbose_name='Estado reproductivo')),
            ],
            options={
                'verbose_name': 'Animal bovino',
                'verbose_name_plural': 'Animales bovinos',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='lotes')),
                ('ha_totales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ha_productivas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_bovinos.campo', verbose_name='Campo')),
            ],
        ),
        migrations.CreateModel(
            name='PadreGenetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('animal_interno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_padre_genetico', to='gestion_bovinos.animalbovino', verbose_name='Animal interno')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padres_geneticos', to='agro.proveedor', verbose_name='Proveedor')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='padres_geneticos', to='gestion_bovinos.razabovino', verbose_name='Raza')),
            ],
            options={
                'verbose_name': 'Padre genético',
                'verbose_name_plural': 'Padres genéticos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='animalbovino',
            name='padre_genetico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='gestion_bovinos.padregenetico', verbose_name='Padre genético'),
        ),
        migrations.AddField(
            model_name='animalbovino',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion_bovinos.razabovino', verbose_name='Raza'),
        ),
        migrations.CreateModel(
            name='Rodeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rodeos', to='gestion_bovinos.establecimiento', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Rodeo',
                'verbose_name_plural': 'Rodeos',
                'ordering': ['nombre'],
                'unique_together': {('establecimiento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoRodeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_rodeo', to='gestion_bovinos.animalbovino', verbose_name='Animal bovino')),
                ('rodeo_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_ingreso', to='gestion_bovinos.rodeo', verbose_name='Rodeo destino')),
                ('rodeo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='gestion_bovinos.rodeo', verbose_name='Rodeo origen')),
            ],
            options={
                'verbose_name': 'Movimiento de rodeo',
                'verbose_name_plural': 'Movimientos de rodeo',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='animalbovino',
            name='rodeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion_bovinos.rodeo', verbose_name='Rodeo'),
        ),
        migrations.CreateModel(
            name='SubRaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subrazas', to='gestion_bovinos.razabovino', verbose_name='Raza')),
            ],
            options={
                'verbose_name': 'Subraza',
                'verbose_name_plural': 'Subrazas',
                'ordering': ['raza', 'orden', 'nombre'],
                'unique_together': {('raza', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='padregenetico',
            name='subraza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='padres_geneticos', to='gestion_bovinos.subraza', verbose_name='Subraza'),
        ),
        migrations.AddField(
            model_name='animalbovino',
            name='subraza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion_bovinos.subraza', verbose_name='Subraza'),
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Variedade')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades', to='gestion_bovinos.cultivo', verbose_name='Cultura')),
            ],
            options={
                'verbose_name': 'Variedade',
                'verbose_name_plural': 'Variedades',
                'ordering': ['cultivo__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(editable=False, max_length=9, verbose_name='Campaña')),
                ('fecha_desde', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha de finalización')),
                ('activa', models.BooleanField(default=False, verbose_name='Campaña activa')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agro_campanas', to='agro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-fecha_desde'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.AddConstraint(
            model_name='animalbovino',
            constraint=models.CheckConstraint(condition=models.Q(('madre', models.F('id')), _negated=True), name='bovino_madre_no_es_self'),
        ),
        migrations.AlterUniqueTogether(
            name='variedad',
            unique_together={('cultivo', 'nombre')},
        ),
    ]
