# Generated by Django 6.0.3 on 2026-04-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0001_initial'),
    ]

    operations = [
    ]
