# Generated by Django 6.0.3 on 2026-04-11 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo_evento', models.CharField(choices=[('VACUNA', 'Vacuna'), ('TRATAMIENTO', 'Tratamiento'), ('DESPARASITACION', 'Desparasitación'), ('OTRO', 'Otro')], default='VACUNA', max_length=20, verbose_name='Tipo de evento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Evento')),
                ('producto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto')),
                ('dosis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dosis')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('requiere_refuerzo', models.BooleanField(default=False, verbose_name='Requiere refuerzo')),
                ('dias_hasta_refuerzo', models.PositiveIntegerField(blank=True, help_text='Ej: 21, 30, 180', null=True, verbose_name='Días hasta refuerzo')),
                ('fecha_refuerzo', models.DateField(blank=True, null=True, verbose_name='Fecha refuerzo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanitarios', to='gestion_bovinos.animalbovino', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Registro sanitario',
                'verbose_name_plural': 'Registros sanitarios',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
