# Generated by Django 6.0.3 on 2026-05-03 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('tipo', models.CharField(choices=[('HORMONA', 'Hormona'), ('ANTIPARASITARIO', 'Antiparasitario'), ('VACUNA', 'Vacuna'), ('ANTIBIOTICO', 'Antibiótico'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['orden', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('categoria', models.CharField(choices=[('REPRODUCTIVO', 'Reproductivo'), ('SANITARIO', 'Sanitario'), ('PRODUCTIVO', 'Productivo'), ('MANEJO', 'Manejo'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20, verbose_name='Categoría')),
                ('aplica_insumo', models.BooleanField(default=False, help_text='Indica si este tipo de evento requiere registrar un producto y dosis.', verbose_name='Aplica insumo')),
            ],
            options={
                'verbose_name': 'Tipo de evento',
                'verbose_name_plural': 'Tipos de evento',
                'ordering': ['orden', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gruposervicio',
            name='orden_tanda',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = primera IA, 2 = segunda IA, 3 = repaso', verbose_name='Orden / tanda'),
        ),
        migrations.CreateModel(
            name='ManejoReproductivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio del servicio')),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_CURSO', 'En curso'), ('DX_PENDIENTE', 'Diagnóstico pendiente'), ('CERRADO', 'Cerrado')], default='PLANIFICADO', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('rodeo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manejos_reproductivos', to='gestion_bovinos.rodeo', verbose_name='Rodeo')),
            ],
            options={
                'verbose_name': 'Manejo reproductivo',
                'verbose_name_plural': 'Manejos reproductivos',
                'ordering': ['-anio', '-fecha_inicio'],
                'unique_together': {('rodeo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoPreñezRodeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha del diagnóstico')),
                ('metodo', models.CharField(choices=[('TACTO', 'Tacto rectal'), ('ECOGRAFIA', 'Ecografía')], max_length=10, verbose_name='Método')),
                ('veterinario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Veterinario')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('manejo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='gestion_bovinos.manejoreproductivo', verbose_name='Manejo reproductivo')),
            ],
            options={
                'verbose_name': 'Diagnóstico de preñez',
                'verbose_name_plural': 'Diagnósticos de preñez',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='gruposervicio',
            name='manejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='gestion_bovinos.manejoreproductivo', verbose_name='Manejo reproductivo'),
        ),
        migrations.CreateModel(
            name='EventoGrupoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('dosis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dosis')),
                ('via_admin', models.CharField(blank=True, choices=[('IM', 'Intramuscular'), ('SC', 'Subcutánea'), ('EV', 'Endovenosa'), ('ORAL', 'Oral'), ('IMPLANTE', 'Implante'), ('OTRO', 'Otro')], max_length=10, null=True, verbose_name='Vía de administración')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('grupo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gestion_bovinos.gruposervicio', verbose_name='Grupo de servicio')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_grupo', to='gestion_bovinos.insumo', verbose_name='Insumo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='gestion_bovinos.tipoevento', verbose_name='Tipo de evento')),
            ],
            options={
                'verbose_name': 'Evento de grupo de servicio',
                'verbose_name_plural': 'Eventos de grupo de servicio',
                'ordering': ['fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoDiagnosticoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('resultado', models.CharField(choices=[('PRENADA', 'Preñada'), ('VACIA', 'Vacía'), ('DUDOSA', 'Dudosa')], max_length=10, verbose_name='Resultado')),
                ('meses_gestacion', models.PositiveSmallIntegerField(blank=True, help_text='Solo para ecografía', null=True, verbose_name='Meses de gestación')),
                ('destino_vacia', models.CharField(blank=True, choices=[('VENTA', 'Venta inmediata'), ('ENGORDE', 'Engorde'), ('REPASO', 'Repaso — nuevo servicio'), ('DESCARTE', 'Descarte')], max_length=10, null=True, verbose_name='Destino (vacía)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_prenez', to='gestion_bovinos.animalbovino', verbose_name='Animal')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='gestion_bovinos.diagnosticopreñezrodeo', verbose_name='Diagnóstico')),
            ],
            options={
                'verbose_name': 'Resultado diagnóstico animal',
                'verbose_name_plural': 'Resultados diagnóstico animales',
                'ordering': ['animal__id'],
                'constraints': [models.UniqueConstraint(fields=('diagnostico', 'animal'), name='resultado_unico_por_diagnostico_animal')],
            },
        ),
    ]
