# Generated by Django 6.0.3 on 2026-04-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0002_registrosanitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosanitario',
            name='dias_hasta_refuerzo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días hasta refuerzo'),
        ),
    ]
