# Generated by Django 6.0.3 on 2026-04-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0002_agregar_numero_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalbovino',
            name='activo',
        ),
    ]
