# Generated by Django 6.0.3 on 2026-05-04 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0002_insumo_tipoevento_gruposervicio_orden_tanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticopreñezrodeo',
            name='grupo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='gestion_bovinos.gruposervicio', verbose_name='Grupo de servicio'),
        ),
        migrations.AlterField(
            model_name='diagnosticopreñezrodeo',
            name='manejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='gestion_bovinos.manejoreproductivo', verbose_name='Manejo reproductivo'),
        ),
    ]
