# Generated by Django 6.0.3 on 2026-05-05 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0003_diagnosticopreñezrodeo_grupo_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventogruposervicio',
            name='padre_genetico',
            field=models.ForeignKey(blank=True, help_text='Requerido para eventos de IA y Repaso.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_grupo', to='gestion_bovinos.padregenetico', verbose_name='Padre genético / Toro'),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='crea_evento_reproductivo',
            field=models.BooleanField(default=False, help_text='Si activo, al registrar este evento en el grupo crea un EventoReproductivo para cada vaca.', verbose_name='Crea evento reproductivo por animal'),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='tipo_evento_reproductivo',
            field=models.CharField(blank=True, choices=[('INSEMINACION', 'Inseminación'), ('SERVICIO_NATURAL', 'Servicio natural')], help_text="Solo aplica si 'Crea evento reproductivo' está activo.", max_length=20, null=True, verbose_name='Tipo de evento reproductivo'),
        ),
        migrations.CreateModel(
            name='AplicacionInsumoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_insumo', to='gestion_bovinos.animalbovino', verbose_name='Animal')),
                ('evento_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_animales', to='gestion_bovinos.eventogruposervicio', verbose_name='Evento de grupo')),
            ],
            options={
                'verbose_name': 'Aplicación de insumo por animal',
                'verbose_name_plural': 'Aplicaciones de insumo por animal',
                'ordering': ['-evento_grupo__fecha'],
                'constraints': [models.UniqueConstraint(fields=('evento_grupo', 'animal'), name='aplicacion_unica_por_evento_animal')],
            },
        ),
    ]
