# Generated by Django 6.0.3 on 2026-04-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0003_remove_animalbovino_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rodeo',
            options={'ordering': ['establecimiento__nombre', 'nombre'], 'verbose_name': 'Rodeo', 'verbose_name_plural': 'Rodeos'},
        ),
        migrations.AddField(
            model_name='rodeo',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad máxima de animales recomendada para este rodeo', null=True, verbose_name='Capacidad'),
        ),
    ]
