# Generated by Django 6.0.3 on 2026-04-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0004_alter_rodeo_options_rodeo_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalbovino',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
