# Generated by Django 6.0.5 on 2026-05-26 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0004_eventogruposervicio_padre_genetico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_sanitario', models.CharField(choices=[('VACUNA', 'Vacuna'), ('TRATAMIENTO', 'Tratamiento'), ('DESPARASITACION', 'Desparasitación'), ('OTRO', 'Otro')], default='VACUNA', max_length=20, verbose_name='Tipo')),
                ('nombre_evento', models.CharField(max_length=100, verbose_name='Nombre del evento')),
                ('dosis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dosis')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('via_admin', models.CharField(blank=True, choices=[('IM', 'Intramuscular'), ('SC', 'Subcutánea'), ('EV', 'Endovenosa'), ('ORAL', 'Oral'), ('IMPLANTE', 'Implante'), ('OTRO', 'Otro')], max_length=10, null=True, verbose_name='Vía de administración')),
                ('requiere_refuerzo', models.BooleanField(default=False, verbose_name='Requiere refuerzo')),
                ('dias_hasta_refuerzo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Días hasta refuerzo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_sanitarias', to='gestion_bovinos.establecimiento', verbose_name='Establecimiento')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_sanitarias', to='gestion_bovinos.insumo', verbose_name='Insumo / Producto')),
            ],
            options={
                'verbose_name': 'Sesión sanitaria',
                'verbose_name_plural': 'Sesiones sanitarias',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='registrosanitario',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='gestion_bovinos.sesionsanitaria', verbose_name='Sesión sanitaria'),
        ),
    ]
