# Generated by Django 6.0.3 on 2026-04-17 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0005_animalbovino_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoreproductivo',
            name='es_efectivo',
            field=models.BooleanField(default=False, verbose_name='Evento efectivo'),
        ),
        migrations.AlterField(
            model_name='medicionanimal',
            name='circunferencia_escrotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Circ. escrotal'),
        ),
        migrations.AlterField(
            model_name='rodeo',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad'),
        ),
        migrations.CreateModel(
            name='ConfigGDPEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('gdp_machos_gramos', models.PositiveIntegerField(default=700, verbose_name='GDP machos (g/día)')),
                ('gdp_hembras_gramos', models.PositiveIntegerField(default=650, verbose_name='GDP hembras (g/día)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('establecimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_gdp', to='gestion_bovinos.establecimiento', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Configuración de GDP',
                'verbose_name_plural': 'Configuraciones de GDP',
            },
        ),
        migrations.CreateModel(
            name='HistorialCategoriaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha del cambio')),
                ('motivo', models.CharField(choices=[('NACIMIENTO', 'Nacimiento'), ('DESTETE', 'Destete'), ('AVANCE_EDAD_PESO', 'Avance por edad / peso'), ('SELECCION', 'Selección fenotípica / genética'), ('CASTRACION', 'Castración — torito a novillito'), ('INGRESO_RODEO', 'Ingreso al rodeo madre'), ('COMPRA', 'Compra / ingreso externo'), ('MANUAL', 'Ajuste manual')], default='MANUAL', max_length=20, verbose_name='Motivo')),
                ('peso_en_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso al cambio (kg)')),
                ('edad_en_cambio_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad al cambio (días)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_categorias', to='gestion_bovinos.animalbovino', verbose_name='Animal')),
                ('categoria_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion_bovinos.categoriabovino', verbose_name='Categoría anterior')),
                ('categoria_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_historial', to='gestion_bovinos.categoriabovino', verbose_name='Categoría nueva')),
            ],
            options={
                'verbose_name': 'Historial de categoría',
                'verbose_name_plural': 'Historial de categorías',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UmbralCambioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('sexo_requerido', models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, null=True, verbose_name='Sexo requerido')),
                ('peso_minimo_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso mínimo (kg)')),
                ('edad_minima_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad mínima (días)')),
                ('requiere_ambos', models.BooleanField(default=False, verbose_name='Requiere peso Y edad')),
                ('motivo_sugerido', models.CharField(choices=[('NACIMIENTO', 'Nacimiento'), ('DESTETE', 'Destete'), ('AVANCE_EDAD_PESO', 'Avance por edad / peso'), ('SELECCION', 'Selección fenotípica / genética'), ('CASTRACION', 'Castración — torito a novillito'), ('INGRESO_RODEO', 'Ingreso al rodeo madre'), ('COMPRA', 'Compra / ingreso externo'), ('MANUAL', 'Ajuste manual')], default='AVANCE_EDAD_PESO', max_length=20, verbose_name='Motivo sugerido')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('categoria_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='umbrales_entrada', to='gestion_bovinos.categoriabovino', verbose_name='Categoría destino')),
                ('categoria_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='umbrales_salida', to='gestion_bovinos.categoriabovino', verbose_name='Categoría origen')),
            ],
            options={
                'verbose_name': 'Umbral de cambio de categoría',
                'verbose_name_plural': 'Umbrales de cambio de categoría',
                'ordering': ['categoria_origen__orden'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciaCambioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('procesada', models.BooleanField(default=False, verbose_name='Procesada')),
                ('aceptada', models.BooleanField(default=False, null=True, verbose_name='Aceptada')),
                ('fecha_procesado', models.DateField(blank=True, null=True, verbose_name='Fecha procesado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_categoria', to='gestion_bovinos.animalbovino', verbose_name='Animal')),
                ('categoria_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sugerencias_entrada', to='gestion_bovinos.categoriabovino', verbose_name='Categoría destino')),
                ('medicion_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_categoria', to='gestion_bovinos.medicionanimal', verbose_name='Medición origen')),
                ('umbral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sugerencias', to='gestion_bovinos.umbralcambiocategoria', verbose_name='Umbral')),
            ],
            options={
                'verbose_name': 'Sugerencia de cambio de categoría',
                'verbose_name_plural': 'Sugerencias de cambio de categoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransicionCategoriaPermitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('sexo_requerido', models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, null=True, verbose_name='Sexo requerido')),
                ('motivo', models.CharField(blank=True, choices=[('NACIMIENTO', 'Nacimiento'), ('DESTETE', 'Destete'), ('AVANCE_EDAD_PESO', 'Avance por edad / peso'), ('SELECCION', 'Selección fenotípica / genética'), ('CASTRACION', 'Castración — torito a novillito'), ('INGRESO_RODEO', 'Ingreso al rodeo madre'), ('COMPRA', 'Compra / ingreso externo'), ('MANUAL', 'Ajuste manual')], max_length=20, null=True, verbose_name='Motivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('categoria_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transiciones_entrada', to='gestion_bovinos.categoriabovino', verbose_name='Categoría destino')),
                ('categoria_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transiciones_salida', to='gestion_bovinos.categoriabovino', verbose_name='Categoría origen')),
            ],
            options={
                'verbose_name': 'Transición de categoría permitida',
                'verbose_name_plural': 'Transiciones de categoría permitidas',
                'ordering': ['categoria_origen__orden', 'categoria_destino__orden'],
                'unique_together': {('categoria_origen', 'categoria_destino', 'motivo', 'sexo_requerido')},
            },
        ),
    ]
