# Generated by Django 6.0.5 on 2026-05-28 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0005_sesionsanitaria_registrosanitario_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFiltroReproductivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('dias_minimos_posparto', models.PositiveIntegerField(default=45, verbose_name='Días mínimos posparto')),
                ('excluir_prenadas', models.BooleanField(default=True, verbose_name='Excluir preñadas')),
                ('edad_minima_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad mínima (días)')),
                ('peso_minimo_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso mínimo (kg)')),
                ('establecimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_filtro_reproductivo', to='gestion_bovinos.establecimiento', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Config. filtro reproductivo',
                'verbose_name_plural': 'Config. filtros reproductivos',
            },
        ),
    ]
