# Generated by Django 6.0.3 on 2026-04-24 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0006_alter_eventoreproductivo_es_efectivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipo_servicio', models.CharField(choices=[('INSEMINACION', 'Inseminación (IATF / IA)'), ('SERVICIO_NATURAL', 'Servicio natural'), ('REPASO', 'Repaso')], default='INSEMINACION', max_length=20, verbose_name='Tipo de servicio')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin_prevista', models.DateField(blank=True, null=True, verbose_name='Fecha fin prevista')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre real')),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_CURSO', 'En curso'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='PLANIFICADO', max_length=15, verbose_name='Estado')),
                ('dias_minimos_posparto', models.PositiveIntegerField(default=45, verbose_name='Días mínimos posparto')),
                ('excluir_prenadas', models.BooleanField(default=True, verbose_name='Excluir preñadas')),
                ('edad_minima_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad mínima (días)')),
                ('peso_minimo_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso mínimo (kg)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_servicio', to='gestion_bovinos.establecimiento', verbose_name='Establecimiento')),
                ('padre_genetico', models.ForeignKey(help_text='Padre único asignado a todo el grupo.', on_delete=django.db.models.deletion.PROTECT, related_name='grupos_servicio', to='gestion_bovinos.padregenetico', verbose_name='Padre genético')),
                ('rodeo', models.ForeignKey(blank=True, help_text='Rodeo desde el cual se pueden cargar animales rápidamente. Opcional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_servicio', to='gestion_bovinos.rodeo', verbose_name='Rodeo base')),
            ],
            options={
                'verbose_name': 'Grupo de servicio',
                'verbose_name_plural': 'Grupos de servicio',
                'ordering': ['-fecha_inicio', '-id'],
                'unique_together': {('establecimiento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MiembroGrupoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_egreso', models.DateField(blank=True, null=True, verbose_name='Fecha de egreso')),
                ('motivo_egreso', models.CharField(blank=True, choices=[('CAMBIO_LOTE', 'Cambio de lote / rodeo'), ('DESCARTE', 'Descarte'), ('PRENADA', 'Confirmada preñada'), ('VACIA', 'Vacía — salida definitiva'), ('MUERTE', 'Muerte'), ('ERROR_CARGA', 'Error de carga'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Motivo de egreso')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias_grupo', to='gestion_bovinos.animalbovino', verbose_name='Animal')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='gestion_bovinos.gruposervicio', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Miembro del grupo',
                'verbose_name_plural': 'Miembros del grupo',
                'ordering': ['-fecha_ingreso', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_egreso__isnull', True)), fields=('grupo', 'animal'), name='miembro_unico_activo_por_grupo')],
            },
        ),
    ]
