# Generated by Django 6.0.5 on 2026-05-28 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0006_config_filtro_reproductivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposervicio',
            name='padre_genetico',
            field=models.ForeignKey(blank=True, help_text='Padre único asignado a todo el grupo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_servicio', to='gestion_bovinos.padregenetico', verbose_name='Padre genético'),
        ),
    ]
