# Generated by Django 5.2 on 2026-06-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0007_padre_genetico_opcional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalbovino',
            name='raza',
        ),
    ]
