# Generated by Django 5.2 on 2026-06-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0009_raza_obligatoria_sin_subraza'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalbovino',
            name='codigo_interno',
            field=models.CharField(blank=True, db_index=True, help_text='ID único generado automáticamente según patrón del establecimiento', max_length=50, null=True, verbose_name='Código interno'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='patron_codigo_interno',
            field=models.CharField(blank=True, help_text="Ej: 'AA-0000' generará AA-0001, AA-0002... o '0000' generará 0001, 0002...", max_length=20, null=True, verbose_name='Patrón código interno animal'),
        ),
    ]
