# Generated by Django 6.0.5 on 2026-06-12 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0010_add_codigo_interno_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalbovino',
            name='subraza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion_bovinos.subraza', verbose_name='Subraza'),
        ),
    ]
