# Generated by Django 6.0.3 on 2026-06-15 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bovinos', '0011_animalbovino_subraza_alter_animalbovino_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalbovino',
            name='raza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion_bovinos.razabovino', verbose_name='Raza'),
            preserve_default=False,
        ),
    ]
