# Generated by Django 6.0.3 on 2026-04-17 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='unidad_default',
        ),
    ]
